name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          config_timezone: Asia/Seoul
          
          base: ""
          
          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # plugin_languages
          plugin_languages: yes
          plugin_languages_skipped: yangeok/yangeok.github.io
          
